# Generated by Django 5.1.5 on 2025-02-10 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_description_remove_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 9, 57, 22, 486011, tzinfo=datetime.timezone.utc)),
        ),
    ]
